# Create a new user
POST http://localhost:3000/api/auth/register HTTP/1.1
Content-Type: application/json

{
  "email": "user@notfound.local",
  "dateBirth": "2012-02-22",
  "firstName": "Keks",
  "lastName": "Smith",
  "password": "123456",
  "avatar": "avatar.test"
}

###

# Get user by ID
GET http://localhost:3000/api/auth/1dd40e5c-73f5-4c34-8117-968783eaacdc HTTP/1.1

###

# Login user by email and password
POST http://localhost:3000/api/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "user@notfound.local",
  "password": "123456"
}

###
